name: Test Suite

on:
  - pull_request

jobs:
  lint-and-unit-tests:
    name: Lint & Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.10", "3.12"]
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
    - name: Install Tox
      run: pip install tox
    - name: Run lint & unit tests
      run: tox

  integration-test:
    name: Integration test with LXD
    runs-on: ubuntu-24.04
    timeout-minutes: 40
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Fix global gitconfig for confined snap
      run: |
        # GH automatically includes the git-lfs plugin and configures it in
        # /etc/gitconfig.  However, the confinement of the charmcraft snap
        # means that it can see that this file exists but cannot read it, even
        # if the file permissions should allow it; this breaks git usage within
        # the snap. To get around this, we move it from the global gitconfig to
        # the user's .gitconfig file.
        cat /etc/gitconfig >> $HOME/.gitconfig
        sudo rm /etc/gitconfig
    - name: Install Dependencies
      run: |
        pip install tox
        sudo snap install core
        sudo snap install lxd --channel=6/stable
        sudo snap install juju --channel=3/stable
        sudo snap install juju-wait --classic
        sudo snap install charmcraft --channel=2.x/stable --classic
        sudo snap install charm --channel=3.x/stable --classic
    - name: Initialize LXD
      run: |
        sudo lxd waitready
        sudo lxd init --auto
        sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
        lxc network set lxdbr0 ipv6.address none
        sudo usermod -a -G lxd $USER

        # Work-around clash between docker and lxd
        # https://github.com/docker/for-linux/issues/1034
        sudo iptables -F FORWARD
        sudo iptables -P FORWARD ACCEPT

    - name: Run integration tests
      run: tox -e integration
